apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  ConnectionAppInsights: <STRING DE CONEXﾃグ DO AZURE APPLICATION INSIGHTS EM BASE 64>
  ConnectionAzureEventHubs: <STRING DE CONEXﾃグ DO AZURE EVENT HUBS EM BASE 64>
  ConnectionAzureStorage: <STRING DE CONEXﾃグ DO AZURE STORAGE EM BASE 64>
  ConnectionSqlServer: <STRING DE CONEXﾃグ DO SQL SERVER EM BASE 64>